import type { Metadata } from "next";
import "./globals.css";
import { audiowide } from "./font";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const audiowide = Audiowide({
//   weight: "400",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   weight: "600",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={audiowide.className}
      >
        {children}
      </body>
    </html>
  );
}
